version: "3"
services:  
  postgres:
    image: postgres:16.0
    restart: always
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "9432:5432"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
  postgraphile:
    image: graphile/postgraphile:4
    restart: always
    ports:
      - "8081:5000"
    depends_on:
      - postgres
    command: "--watch --simple-collections only"
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
  graphql-mesh:
    build: .
    restart: always
    ports:
      - "8080:4000"
    depends_on:
      - postgraphile
    volumes:
      - "./.meshrc.yaml:/root/.meshrc.yaml:ro"
    environment:
      DEBUG: 1
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
