version: "3.6"
services:
  postgres:
    image: postgres:16
    ports:
      - "${PGPORT:-5432}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    command: "postgres -c 'shared_preload_libraries=pg_stat_statements'"
  graphql-engine:
    image: hasura/graphql-engine:v2.37.0.cli-migrations-v3
    ports:
      - "${HGEPORT:-8080}:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_READONLY_URL: "postgres://${PGREADUSER:-postgres}:${PGREADPASSWORD:-postgres}@postgres/${PGDATABASE}"
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@postgres/${PGDATABASE}"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    volumes:
      - "./metadata:/hasura-metadata:ro"
