version: "3.6"
services:
  postgres:
    image: postgres:16
    ports:
      - ${PGPORT:-5432}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
    volumes:
      - ./initdb.d-postgres:/docker-entrypoint-initdb.d:ro
    command: postgres -c 'shared_preload_libraries=pg_stat_statements'
    healthcheck:
      test: psql -d graphql_engine_2 -U postgres -c 'select 1' || exit 1
  graphql-engine-1:
    image: hasura/graphql-engine:v2.37.0.cli-migrations-v3
    ports:
      - ${HGEPORT:-8080}:8080
    restart: always
    environment:
      DATABASE_URL: postgres://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@postgres/${PGDATABASE}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_READONLY_URL: postgres://${PGREADUSER:-postgres}:${PGREADPASSWORD:-postgres}@postgres/${PGDATABASE}
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@postgres/graphql_engine_1
    volumes:
      - ./metadata:/hasura-metadata:ro
    depends_on:
       postgres:
         condition: service_healthy
