version: "3.6"
services:
  postgres:
    image: postgres:16
    ports:
      - "${PGPORT}:5432"
    restart: always
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      interval: 10s
      retries: 100
      test: ["CMD-SHELL", "psql -h localhost -U postgres -d postgres -c 'select count(*) from order_detail'"]
      timeout: 300s
  graphql-engine:
    image: hasura/graphql-engine:v2.36.0.cli-migrations-v3
    ports:
      - "${HGEPORT}:8080"
    restart: always
    volumes:
      - "./metadata:/hasura-metadata:ro"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    depends_on:
       postgres:
         condition: service_healthy
