version: "3.6"
services:
  metadata:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  data:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.30.0.cli-migrations-v3
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./metadata:/hasura-metadata
      - ./migrations:/hasura-migrations
    environment:
      DATA_URL: postgres://postgres:postgres@data:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@metadata:5432/postgres


