version: "3.7"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  hasura:
    image: hasura/graphql-engine:v2.33.3.cli-migrations-v3
    restart: always
    ports:
      - "${HGE_PORT}:8080"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_EE_LICENSE_KEY: "${HASURA_GRAPHQL_EE_LICENSE_KEY}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
      SNOWFLAKE_URL: "${SNOWFLAKE_URL}"
    volumes:
      - ./metadata:/hasura-metadata
    depends_on:
      data-connector-agent:
        condition: service_healthy
  data-connector-agent:
    image: hasura/graphql-data-connector:v2.33.3
    restart: always
    environment:
      QUARKUS_LOG_LEVEL: ERROR
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/snowflake/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
