version: "3.6"
services:
  postgres:
    build: .
    ports:
      - ${PGPORT:-5433}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.d-postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: "pg_isready -U postgres"
  graphql-engine:
    image: hasura/graphql-engine:v2.40.0
    ports:
      - ${HGEPORT:-8081}:8080
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
    depends_on:
      postgres:
        condition: service_healthy
