version: "3.6"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./initdb.d-postgres:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "${POSTGRES_PORT}:5432"

