version: '3.6'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - "./hasura/metadata:/hasura-metadata:ro"
      - "./hasura/migrations:/hasura-migrations:ro"
    environment:
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://hasurauser:hasurauser@postgres:5432/postgres

