version: "3.6"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "${MSSQL_SA_USER}", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "select DB_NAME()"]
      start_period: 10s
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports: 
      - "1433:1433"
  mssql_init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: "no"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "mssql", "-U", "${MSSQL_SA_USER}", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "select * from person"]
    depends_on:
      mssql:
        condition: service_healthy
    entrypoint: ["/opt/mssql-tools/bin/sqlcmd", "-S", "mssql", "-U", "${MSSQL_SA_USER}", "-P", "${MSSQL_SA_PASSWORD}", "-i", "/init_mssql.sql"]
    volumes:
      - ./init_mssql.sql:/init_mssql.sql
  postgres:
    image: toleg/postgres_mssql_fdw
    restart: always
    command: "postgres -c custom.sa_password=${MSSQL_SA_PASSWORD}"
    depends_on:
      mssql_init:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "9432:5432"
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
  graphql-engine:
    image: hasura/graphql-engine:v2.17.0
    restart: always
    depends_on:
      - postgres
    ports:
      - "9080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${PGUSER}:${PGPASSWORD}@postgres:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
