version: '2'

volumes:
  yb-master-data-1:
  yb-tserver-data-1:

services:
  yb-master:
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --advertise_address=yb-master
    ports:
      - "5433:5433"
      - "7000:7000"
      - "9000:9000"
      - "9042:9042"
    restart: always
  yb-tserver-1:
    depends_on:
      - yb-master
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --join yb-master --advertise_address=yb-tserver-1
    restart: always
  yb-tserver-2:
    depends_on:
      - yb-master
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --join yb-master --advertise_address=yb-tserver-2
    restart: always
  yb-tserver-3:
    depends_on:
      - yb-master
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --join yb-master --advertise_address=yb-tserver-3
    restart: always
