version: '3.6'
services:
services:
  yb-master:
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --advertise_address=yb-master
    ports:
      - "5433:5433"
      - "7000:7000"
      - "9000:9000"
      - "9042:9042"
    restart: always
  yb-tserver-1:
    depends_on:
      - yb-master
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --join yb-master --advertise_address=yb-tserver-1
    restart: always
  yb-tserver-2:
    depends_on:
      - yb-master
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --join yb-master --advertise_address=yb-tserver-2
    restart: always
  yb-tserver-3:
    depends_on:
      - yb-master
    image: yugabytedb/yugabyte:latest
    command: bin/yugabyted start --background=false --join yb-master --advertise_address=yb-tserver-3
    restart: always
  # postgres:
  #   image: postgres:14
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.13.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:

