version: "3.6"
services:
  postgres:
    image: postgres:15
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.33.0
    ports:
      - "${HGEPORT}:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
