table:
  name: application
  schema: user
array_relationships:
  - name: roles
    using:
      foreign_key_constraint_on:
        column: application_id
        table:
          name: role
          schema: user
