version: '3.6'
services:
  postgres:
    image: dventimiglia/postgresqlml
    ports:
      - "${PGPORT}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command:
      - sleep
      - infinity
  graphql-engine:
    image: hasura/graphql-engine
    ports:
      - "${HGEPORT}:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
