version: "3.7"
services:
  subgraph_approval_mongodb:
    image: mongo:6
    restart: always
    ports:
      - ${MONGODBPORT}:27017
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
    volumes:
      - ./initdb.d_mongodb:/docker-entrypoint-initdb.d:ro
  subgraph_approval_postgres:
    build: .
    depends_on:
      - subgraph_approval_mongodb
    ports:
      - ${PGPORT1}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.d_postgres:/docker-entrypoint-initdb.d:ro
  subgraph_approval_mongodb_data_connector:
    image: hasura/mongo-data-connector:v2.38.0
    depends_on:
      - subgraph_approval_mongodb
    restart: always
  subgraph_approval_hasura:
    image: hasura/graphql-engine:v2.38.0.cli-migrations-v3
    depends_on:
      - subgraph_approval_postgres
      - subgraph_approval_mongodb_data_connector
    restart: always
    ports:
      - ${HGPORT1}:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/healthz"]
      start_period: 60s
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@subgraph_approval_postgres/postgres
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_MAX_CACHE_SIZE: 200
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"Mongo":{"uri":"http://subgraph_approval_mongodb_data_connector:3000"}}}}'
    volumes:
      - ./metadata:/hasura-metadata:ro
