version: 3
endpoint: https://patient-jennet-24.hasura.app
admin_secret: 7zC8wPRgG0OejVnaUjjiQ5JNEaGPefa4YMx8LFUl5L24jGJ9zUhslRp1gcah0uZy
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
