version: 3
endpoint: https://better-viper-16.hasura.app
admin_secret: Z14WyXv5sfgnzXa4Y3HMUnCpM7jabe5wUBdzOKbf9sIq5Kgk1koihAHGCGlMQo4p
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
