version: 3
endpoint: https://advanced-mackerel-45.hasura.app
admin_secret: aQSYzeqb5utVX7wwmwBM7b0EvCHHyqUvaw6fp9F3DK02jp1e3DUydXv7jlqoPcpY
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
