version: "3.6"
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      DEFAULT_POOL_SIZE: 20
      MIN_POOL_SIZE: 10
      ADMIN_USERS: postgres
      POOL_MODE: session
      AUTH_TYPE: plain
      APPLICATION_NAME_ADD_HOST: 1
      SERVER_ROUND_ROBIN: 1
      SERVER_IDLE_TIMEOUT: 30
  load-balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - "graphql-engine-1"
      - "graphql-engine-2"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  graphql-engine-1:
    image: hasura/graphql-engine:v2.16.1
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
      - "redis"
      - "pgbouncer"
    restart: always
    environment:
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@pgbouncer:5432/postgres
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_APIS: "graphql,metadata,config,developer,pgdump,metrics"
      HASURA_GRAPHQL_METRICS_SECRET: ${HASURA_GRAPHQL_METRICS_SECRET}
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
      HASURA_GRAPHQL_REDIS_URL: "redis://redis:6379"
      HASURA_GRAPHQL_RATE_LIMIT_REDIS_URL: "redis://redis:6379"
      HASURA_GRAPHQL_MAX_CACHE_SIZE: "200"
  graphql-engine-2:
    image: hasura/graphql-engine:v2.16.1
    ports:
      - "8082:8080"
    depends_on:
      - "postgres"
      - "redis"
    restart: always
    environment:
      PG_DATABASE_URL: postgres://postgres:postgrespassword@pgbouncer:5432/postgres
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_APIS: "graphql,metadata,config,developer,pgdump,metrics"
      HASURA_GRAPHQL_METRICS_SECRET: ${HASURA_GRAPHQL_METRICS_SECRET}
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
      HASURA_GRAPHQL_REDIS_URL: "redis://redis:6379"
      HASURA_GRAPHQL_RATE_LIMIT_REDIS_URL: "redis://redis:6379"
      HASURA_GRAPHQL_MAX_CACHE_SIZE: "200"
