version: "3.6"
services:
  postgres:
    image: postgres:15
    ports:
      - "${PGPORT}:5432"
    restart: always
    volumes:
      - "./initdb.d-postgres:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.35.0.cli-migrations-v3
    ports:
      - "${HGEPORT}:8080"
    restart: always
    volumes:
      - "./metadata:/hasura-metadata:ro"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "host=postgres port=5432 dbname=postgres user=postgres password=postgres options='-c user.name=davidaventimiglia'"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

