version: '3.6'
services:
  metadata:                     # Put Hasura metadata into its own db.
    image: postgres:14
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  origin:                       # Data warehouse data source db
    image: postgres:14
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  cache:                        # Read-through cache db
    build: .
    ports:
      - "5436:5432"
    depends_on:
      - "origin"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
    volumes:
      - ./cache-init:/docker-entrypoint-initdb.d
  graphql-engine:               # Hasura instance
    image: hasura/graphql-engine:v2.15.1
    ports:
      - "8080:8080"
    depends_on:
      - "metadata"
      - "cache"
    restart: always
    environment:
      PG_DATABASE_URL: postgres://postgres:postgrespassword@cache:5432/postgres
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@metadata:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log



