table:
  name: product
  schema: public
event_triggers:
  - name: product_create
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: https://{{ALGOLIA_APPLICATION_ID}}-dsn.algolia.net/1/indexes/{{ALGOLIA_INDEX_NAME}}/
    headers:
      - name: X-Algolia-API-Key
        value_from_env: ALGOLIA_API_KEY
      - name: X-Algolia-Application-Id
        value_from_env: ALGOLIA_APPLICATION_ID
    request_transform:
      body:
        action: transform
        template: '{"name": {{$body.event.data.new.name}}}'
      method: PUT
      query_params: {}
      template_engine: Kriti
      url: '{{$base_url}}{{$body.id}}'
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
