version: '3.6'
services:
  postgres_1:
    image: postgres:14
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  postgres_2:
    image: postgres:14
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  metadata:
    image: postgres:14
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.14.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres_1"
      - "postgres_2"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@metadata:5432/postgres
      PG_DATABASE_URL_POSTGRES_1: postgres://postgres:postgrespassword@postgres_1:5432/postgres
      PG_DATABASE_URL_POSTGRES_1: postgres://postgres:postgrespassword@postgres_2:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log



