version: "3.6"
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8080:8978"
    volumes:
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
    restart: always
  graphql-engine:
    build: .
    ports:
      - "8081:8080"
      - "5433:5432"
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - "1522:1521"
      - "5501:5500"
  db2:
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "db2inst1"
      DB2INST1_PASSWORD: "password"
      DBNAME: "testdb"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "true"
      HADR_ENABLED: "false"
    ports:
      - "50001:50000"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3307:3306"
