version: "3.6"
services:
  graphql-engine:
    build: .
    ports:
      - "8080:8080"
      - "5433:5432"
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8081:8978"
    volumes:
      - ./cloudbeaver/conf:/opt/cloudbeaver/conf
    restart: always
    environment:
      CB_SERVER_NAME: test
      CB_ADMIN_NAME: test
      CB_ADMIN_PASSWORD: test
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: chinook
      POSTGRES_USER: chinook
      POSTGRES_DB: chinook
    volumes:
      - ./chinook_postgres:/docker-entrypoint-initdb.d
  oracle:
    image: gvenzl/oracle-xe
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: chinook
      ORACLE_DATABASE: chinook
      APP_USER: chinook
      APP_USER_PASSWORD: chinook
    volumes:
      - ./chinook_oracle:/docker-entrypoint-initdb.d
  db2:
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "chinook"
      DB2INST1_PASSWORD: "chinook"
      DBNAME: "chinook"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "true"
      REPODB: "false"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "true"
      HADR_ENABLED: "false"
    ports:
      - "50001:50000"
    volumes:
      - ./chinook_db2:/var/custom
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "chinook"
      MYSQL_USER: "chinook"
      MYSQL_PASSWORD: "chinook"
      MYSQL_ROOT_PASSWORD: "chinook"
    ports:
      - "3307:3306"
    volumes:
      - ./chinook_mysql:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
