version: "3.6"
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8080:8978"
    volumes:
      - ./cloudbeaver/conf:/opt/cloudbeaver/conf
    restart: always
    environment:
      CB_SERVER_NAME: test
      CB_ADMIN_NAME: test
      CB_ADMIN_PASSWORD: test
  graphql-engine:
    build: .
    ports:
      - "8081:8080"
      - "5433:5432"
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: hasura
      POSTGRES_USER: hasura
      POSTGRES_DB: hasura
  oracle:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: hasura
      ORACLE_DATABASE: hasura
      APP_USER: hasura
      APP_USER_PASSWORD: hasura
  db2:
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "hasura"
      DB2INST1_PASSWORD: "hasura"
      DBNAME: "hasura"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "true"
      HADR_ENABLED: "false"
    ports:
      - "50001:50000"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "hasura"
      MYSQL_USER: "hasura"
      MYSQL_PASSWORD: "hasura"
      MYSQL_ROOT_PASSWORD: "hasura"
    ports:
      - "3307:3306"
