version: "3.6"
services:
  postgres:
    build: .
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "15432:5432"
    restart: always
    command: "postgres -c shared_preload_libraries=bloom"
    environment:
      POSTGRES_PASSWORD: postgres
