version: "3.7"
services:
  supergraph_logic_postgres:
    build: .
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  supergraph_logic_hasura:
    image: hasura/graphql-engine:v2.38.0.cli-migrations-v3
    depends_on:
      - supergraph_logic_postgres
    restart: always
    ports:
      - 8084:8080
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@supergraph_gateway_postgres/postgres
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_EE_LICENSE_KEY: ${HASURA_GRAPHQL_EE_LICENSE_KEY}
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_MAX_CACHE_SIZE: 200
  supergraph_logic_postgrest:
    image: postgrest/postgrest
    depends_on:
      - supergraph_logic_postgres
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@supergraph_logic_postgres:5432/postgres
