version: '3.6'
services:
  postgres:
    image: postgres:16
    ports:
      - "${PGPORT}:5432"
    restart: always
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine-manager:
    image: hasura/graphql-engine:v2.35.0-ce.cli-migrations-v3
    ports:
      - "${HGEPORT1}:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - "./hasura/metadata:/hasura-metadata:ro"
    environment:
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  graphql-engine-user:
    image: hasura/graphql-engine:v2.35.0-ce
    ports:
      - "${HGEPORT2}:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - "./hasura/metadata:/hasura-metadata:ro"
    environment:
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres

