version: '3.6'
services:
  postgres:
    build: .
    ports:
      - "5436:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command: [
    "postgres",
    "-c", "custom.jdbc_driver=${JDBC_DRIVER}",
    "-c", "custom.jdbc_jarfile=${JDBC_JARFILE}",
    "-c", "custom.jdbc_password=${JDBC_PASSWORD}",
    "-c", "custom.jdbc_url=${JDBC_URL}",
    "-c", "custom.jdbc_user=${JDBC_USER}"
    ]
  graphql-engine:
    image: hasura/graphql-engine:v2.15.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log



